### ISSUE TITLE
Check 130 crore plus key

### ISSUE THREAD

**Issue by ashraful1980** [iceland2k14/btc_words#1]
Hi,
I have check 130 crore plus key; no positive result yet...

![result](https://user-images.githubusercontent.com/52574658/112643265-62332d80-8e6e-11eb-8891-22cf2174a5c0.jpg)

**Comment by iceland2k14** [comment]
Mnemonics are generated Random. Chance to collide an address is very slim. 
If your Address list is big enough to have Dormant and Lost address. One day you may hit something. Good Luck.

**Comment by ashraful1980** [comment]
Thanks for your quick response.

please adding gmpy2 & secp256k1; it maybe found more speed.....

**Comment by iceland2k14** [comment]
I will see what can be improved, each function. Just now updated the mnemonic generation x100 times faster. Overall x2
