### ISSUE TITLE
Seed_puzzle

### ISSUE THREAD

**Issue by roi35** [iceland2k14/btc_words#4]
Hello I found something under the number 049. I can't understand there two lines of the first private key or an address in the hash160 format? second line of Seed Candidate. how and where to see them?

**Comment by iceland2k14** [comment]
Hi, The script was not completely polished. Currently it checks only if the seed can match the Puzzle 20 PrivateKey. I will add sequential match that if same seed can match 10 PrivateKeys from Puzzle 20 to 30 then it would be most likely be the Solution. And could get all the remaining 86 unsolved Privatkeys.

For you, what is you get is the seed. In this website BIP39 seed [https://iancoleman.io/bip39/](https://iancoleman.io/bip39/)  

Till i have not finished. You need to do it manually.
So create Total 160 Privatekys using this seed and mask those privatkeys 1 by 1 using this `int('1'+bin(int(line,16))[2:][-k:],2)` here vary the k from 10 to 160 for checking. Then check if those masked Privatekeys matches with the Actual Known Privatekeys of the Puzzle. 10 to 63. 

If yes, then WoW..... You can Withdraw >100 BTC Prize

**Comment by roi35** [comment]
I'm not a programmer, but it will be difficult for me .. ((if we could somehow automate this process ..

**Comment by iceland2k14** [comment]
Updated the masked key results after success.
