### ISSUE TITLE
ошибки bitcoinlib

### ISSUE THREAD

**Issue by Vladimir855** [iceland2k14/btc_words#5]
добавить requirements.txt  не устанавливается pip install bitcoinlib выдает ошибки

**Comment by iceland2k14** [comment]
The main library is here. [https://github.com/1200wd/bitcoinlib](https://github.com/1200wd/bitcoinlib)
In which setup this module is not installing ? Windows, Linux, Termux ??

**Comment by Vladimir855** [comment]
ubuntu 18

**Comment by iceland2k14** [comment]
Please open a issue in their github if it is not installing for you

**Comment by Ak535Ak** [comment]
> добавить requirements.txt не устанавливается pip install bitcoinlib выдает ошибки

решилось использованием pip3 вместо pip в моем случае
