### ISSUE TITLE
Seed_puzzle

### ISSUE THREAD

**Issue by Vladimir855** [iceland2k14/btc_words#6]
Ошибка 
![Снимок экрана_2021-08-03_10-30-01](https://user-images.githubusercontent.com/48643229/127959267-136bd90d-3f60-4842-93fb-cf13251ea367.png)

**Comment by Vladimir855** [comment]
что за ошибка

**Comment by iceland2k14** [comment]
Yeah it's a bug. I need to upgrade this script, if last element is match with key then list will have no more elements and crash.
Also it is super slow currently. I have to make it faster. 
Maybe in few months.
