### ISSUE TITLE
entropy_bits

### ISSUE THREAD

**Issue by Vladimir855** [iceland2k14/btc_words#7]
Что означает 128, 160 ..... как поменять язык и количество, вместо 12 - 24?

**Comment by Noname400** [comment]
128 бит = 12 слов
256 бит = 24 слов

**Comment by Noname400** [comment]
смена языка:
1. заменить значение переменной wordlist
2. загрузить список слов написав небольшой код
with open('czech.txt', "r") as fp:
        txt = fp.readlines()
[czech.txt](https://github.com/iceland2k14/btc_words/files/6921134/czech.txt)
[english.txt](https://github.com/iceland2k14/btc_words/files/6921135/english.txt)
[french.txt](https://github.com/iceland2k14/btc_words/files/6921136/french.txt)
[italian.txt](https://github.com/iceland2k14/btc_words/files/6921137/italian.txt)
[japanese.txt](https://github.com/iceland2k14/btc_words/files/6921138/japanese.txt)
[korean.txt](https://github.com/iceland2k14/btc_words/files/6921139/korean.txt)
[spanish.txt](https://github.com/iceland2k14/btc_words/files/6921140/spanish.txt)
[chinese_simplified.txt](https://github.com/iceland2k14/btc_words/files/6921141/chinese_simplified.txt)
[chinese_traditional.txt](https://github.com/iceland2k14/btc_words/files/6921142/chinese_traditional.txt)

**Comment by iceland2k14** [comment]
Thank you @Noname400
