### ISSUE TITLE
Test Result

### ISSUE THREAD

**Issue by ken2709** [iceland2k14/btc_words#8]
How i can do test a result ?
Thanks

**Comment by iceland2k14** [comment]
### For bip44_words script
change Line 141 to your known mnemonics and Line 151 to the strength of that mnemonics. 
https://github.com/iceland2k14/btc_words/blob/441387ea4c079dd52fa1f8aa31fafe459327ecab/bip44_words_mcpu.py#L141
https://github.com/iceland2k14/btc_words/blob/441387ea4c079dd52fa1f8aa31fafe459327ecab/bip44_words_mcpu.py#L151
Add your address in the address file to search and run.

### For Seed Puzzle script
its a concept to find the mnemonic of wallet used to fund >100 BTC puzzle address. if a match is found we can get all unsolved 86 puzzles privatekey. there is no way to test it.

**Comment by ken2709** [comment]
@iceland2k14 many thank for your information.
i try some edit but not correct.
which format for that please? i am not coder master.
 mnem = 'abandon','ability','able','about','above','absent','absorb','abstract','absurd','abuse','access','accident'(entropy_bits) 
 mnem = ('abandon','ability','able','about','above','absent','absorb','abstract','absurd','abuse','access','accident'(entropy_bits))
...

**Comment by iceland2k14** [comment]
mnem = 'upgrade often leader quote spike outside mail below eagle razor torch boost'
entropy_bits = 128
